#!/bin/sh
rm -f tests_autogen.asm
results=($(grep -o "\btest__[a-zA-Z0-9_]*:" 11.parse.test.asm | sed "s/://g"))

exec 3>&1

exec > "tests_autogen.asm"

echo "; -------"
echo "; WARNING: This file is auto-generated by 'tests_autogen.sh'"
echo "; -------"
echo ""

echo "; ----------"
echo "; test names"
echo "; ----------"
for i in "${!results[@]}"; do
  name="${results[i]/test__/name__}:"
  echo "${name}"
  echo "!pet \"${results[i]}:\", \$00"
done

echo ""
echo "; ----------"
echo "; test array"
echo "; ----------"
echo "test_array:"
for i in "${!results[@]}"; do

  name="${results[i]/test__/name__}"
  echo "!word ${name}"
  echo "!word ${results[i]}"
done
echo "!word \$0000"
echo "!word \$0000"

exec 1>&3
echo "Output written to 'tests_autogen.asm'"
